package com.pomelofashion.pomelopickup.domain.model

data class PickupLocation(
    val feature: String = "",
    val idPickupLocation: Int = 0,
    val idCountry: Int = 0,
    val idState: Int = 0,
    val idCarrier: Int = 0,
    val company: String = "",
    val npsLink: String = "",
    val alias: String = "",
    val address1: String = "",
    val address2: String = "",
    val district: String = "",
    val city: String = "",
    val postcode: Int = 0,
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val phone: String = "",
    val nearestBts: String = "",
    val notableArea: String = "",
    val hours1: String = "",
    val hours2: String = "",
    val hours3: String = "",
    val description: String = "",
    val isFeatured: Boolean = false,
    val subtype: String = "",
    val storeImagePath: String = "",
    val floormapImagePath: String = "",
    val active: Boolean = false,
    val floorNumber: Int = 0,
    val status: String = "",
    val idZone: Int = 0,
    val isNewLocation: Boolean = false,
    val type: String = "",
    val hours: List<String> = emptyList(),
    val isDefaultLocation: Boolean = false,
) {
    val isDataValid = idPickupLocation != 0 && alias.isNotEmpty()
}